# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Cleaning day')),
                ('signature', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CleanTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskType', models.CharField(max_length=50)),
                ('numberTimes', models.IntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaning.CleanDay')),
            ],
        ),
        migrations.CreateModel(
            name='CleanType',
            fields=[
                ('cleanID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('taskDone', models.BooleanField(default=False)),
            ],
        ),
    ]
