# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanday',
            name='describtion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
