# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='frys', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('defrosted', models.BooleanField(default=False)),
                ('isClean', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='unit',
        ),
        migrations.AddField(
            model_name='fridge',
            name='isClean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='type',
            field=models.CharField(default='kylskåp', max_length=50),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
