# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cleaning', '0003_auto_20161112_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isClean', models.BooleanField(default=False)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='freezer',
            name='defrosted',
        ),
        migrations.RemoveField(
            model_name='freezer',
            name='isClean',
        ),
        migrations.RemoveField(
            model_name='freezer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='isClean',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='type',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='object_id',
        ),
        migrations.AddField(
            model_name='freezer',
            name='freezer_type',
            field=models.CharField(default='Glassfrys', max_length=50),
        ),
        migrations.AddField(
            model_name='fridge',
            name='fridge_type',
            field=models.CharField(default='Kylskåp', max_length=50),
        ),
        migrations.AddField(
            model_name='temperature',
            name='defrosted',
            field=models.BooleanField(default=False),
        ),
    ]
