# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0004_auto_20161113_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clean',
            old_name='unit',
            new_name='content_type',
        ),
        migrations.AddField(
            model_name='clean',
            name='content_id',
            field=models.IntegerField(default=0),
        ),
    ]
