# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cleaning', '0005_auto_20161113_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='clean',
            name='content_id',
            field=models.PositiveIntegerField(null=True, verbose_name='related object'),
        ),
        migrations.AlterField(
            model_name='clean',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content page'),
        ),
    ]
