# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 19:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleaning', '0006_auto_20161113_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.BooleanField(default=False)),
                ('open', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Golv',
                'verbose_name_plural': 'Golven',
            },
        ),
        migrations.CreateModel(
            name='FreezerTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured', models.IntegerField()),
                ('defrosted', models.BooleanField(default=False)),
                ('anomaly', models.BooleanField(default=False)),
                ('cleaned', models.BooleanField()),
                ('active', models.BooleanField(default=True)),
                ('prescribedMaxTempFridge', models.PositiveIntegerField(default=8)),
                ('prescribedMinTempFridge', models.PositiveIntegerField(default=4)),
                ('prescribedMaxTempFreezer', models.IntegerField(default=-4)),
                ('prescribedMinTempFreezer', models.IntegerField(default=-20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frys',
                'verbose_name_plural': 'Frysar',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FridgeTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured', models.IntegerField()),
                ('defrosted', models.BooleanField(default=False)),
                ('anomaly', models.BooleanField(default=False)),
                ('cleaned', models.BooleanField()),
                ('active', models.BooleanField(default=True)),
                ('prescribedMaxTempFridge', models.PositiveIntegerField(default=8)),
                ('prescribedMinTempFridge', models.PositiveIntegerField(default=4)),
                ('prescribedMaxTempFreezer', models.IntegerField(default=-4)),
                ('prescribedMinTempFreezer', models.IntegerField(default=-20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kyl',
                'verbose_name_plural': 'Kylar',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.BooleanField(default=False)),
                ('open', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Köket',
            },
        ),
        migrations.RemoveField(
            model_name='clean',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='content',
        ),
        migrations.AlterField(
            model_name='freezer',
            name='freezer_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='fridge_type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Clean',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.AddField(
            model_name='fridgetemp',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cleaning.Fridge'),
        ),
        migrations.AddField(
            model_name='freezertemp',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cleaning.Freezer'),
        ),
    ]
