# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0007_auto_20161113_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freezer',
            options={'verbose_name': 'Frys', 'verbose_name_plural': 'Frysar'},
        ),
        migrations.AlterModelOptions(
            name='freezertemp',
            options={'ordering': ['date'], 'verbose_name': 'Kontrollpunkt frys', 'verbose_name_plural': 'Kontrollpunkter frysar'},
        ),
        migrations.AlterModelOptions(
            name='fridge',
            options={'verbose_name': 'Kyl', 'verbose_name_plural': 'Kylar'},
        ),
        migrations.AlterModelOptions(
            name='fridgetemp',
            options={'ordering': ['date'], 'verbose_name': 'Kontrollpunkt kylskåp', 'verbose_name_plural': 'Kontrollpunkter kylskåp'},
        ),
        migrations.RemoveField(
            model_name='freezertemp',
            name='active',
        ),
        migrations.RemoveField(
            model_name='fridgetemp',
            name='active',
        ),
        migrations.AddField(
            model_name='freezer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fridge',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
