# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 22:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0008_auto_20161113_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freezer',
            options={'ordering': ['active'], 'verbose_name': 'Frys', 'verbose_name_plural': 'Frysar'},
        ),
        migrations.AlterModelOptions(
            name='fridge',
            options={'ordering': ['active'], 'verbose_name': 'Kyl', 'verbose_name_plural': 'Kylar'},
        ),
        migrations.AddField(
            model_name='fridge',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Är den aktiv?'),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='freezer_type',
            field=models.CharField(max_length=50, verbose_name='Typ av frys'),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Plats'),
        ),
        migrations.AlterField(
            model_name='freezertemp',
            name='anomaly',
            field=models.BooleanField(default=False, verbose_name='avvikelse'),
        ),
        migrations.AlterField(
            model_name='freezertemp',
            name='cleaned',
            field=models.BooleanField(verbose_name='Städat'),
        ),
        migrations.AlterField(
            model_name='freezertemp',
            name='defrosted',
            field=models.BooleanField(default=False, verbose_name='Avfrostad'),
        ),
        migrations.AlterField(
            model_name='freezertemp',
            name='measured',
            field=models.IntegerField(verbose_name='Uppmätt temperatur'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Är den aktiv?'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='fridge_type',
            field=models.CharField(max_length=50, verbose_name='Typ av kyl'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Plats'),
        ),
        migrations.AlterField(
            model_name='fridgetemp',
            name='anomaly',
            field=models.BooleanField(default=False, verbose_name='avvikelse'),
        ),
        migrations.AlterField(
            model_name='fridgetemp',
            name='cleaned',
            field=models.BooleanField(verbose_name='Städat'),
        ),
        migrations.AlterField(
            model_name='fridgetemp',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='datum'),
        ),
        migrations.AlterField(
            model_name='fridgetemp',
            name='defrosted',
            field=models.BooleanField(default=False, verbose_name='Avfrostad'),
        ),
        migrations.AlterField(
            model_name='fridgetemp',
            name='measured',
            field=models.IntegerField(verbose_name='Uppmätt temperatur'),
        ),
        migrations.AlterField(
            model_name='fridgetemp',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Signatur'),
        ),
        migrations.AlterField(
            model_name='fridgetemp',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cleaning.Fridge', to_field='name', verbose_name='Enhet'),
        ),
        migrations.AlterUniqueTogether(
            name='fridge',
            unique_together=set([('fridge_type', 'location')]),
        ),
    ]
