# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0009_auto_20161113_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezertemp',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cleaning.Freezer', verbose_name='Typ av frys'),
        ),
        migrations.AlterField(
            model_name='fridgetemp',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cleaning.Fridge', verbose_name='Enhet'),
        ),
    ]
