# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0010_auto_20161114_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='name',
        ),
    ]
