# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0011_remove_fridge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezertemp',
            name='comment',
            field=models.TextField(blank=True, max_length=255, verbose_name='kommentar'),
        ),
        migrations.AddField(
            model_name='fridgetemp',
            name='comment',
            field=models.TextField(blank=True, max_length=255, verbose_name='kommentar'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Economy.Employee'),
        ),
        migrations.AlterField(
            model_name='freezertemp',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Economy.Employee'),
        ),
        migrations.AlterField(
            model_name='fridgetemp',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Economy.Employee', verbose_name='Signatur'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Economy.Employee'),
        ),
    ]
