# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0013_auto_20161122_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freezer',
            options={'ordering': ['-active'], 'verbose_name': 'Frys', 'verbose_name_plural': 'Frysar'},
        ),
        migrations.AlterModelOptions(
            name='freezertemp',
            options={'ordering': ['-date'], 'verbose_name': 'Kontrollpunkt frys', 'verbose_name_plural': 'Kontrollpunkter frysar'},
        ),
        migrations.AlterModelOptions(
            name='fridge',
            options={'ordering': ['-active'], 'verbose_name': 'Kyl', 'verbose_name_plural': 'Kylar'},
        ),
        migrations.AlterField(
            model_name='freezertemp',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Economy.Employee', verbose_name='Signatur'),
        ),
    ]
