# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 16:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('card', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('cafeSales', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('iceCreamSales', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('foodShopSales', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bikeSales', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('booksSales', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('other12Sales', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('other25Sales', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('comment', models.CharField(max_length=150)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
