# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Economy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cashier',
            new_name='Dagskassa',
        ),
    ]
