# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Economy', '0002_auto_20161112_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('personNo', models.IntegerField()),
                ('wage', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'anställda',
                'verbose_name': 'anställd',
            },
        ),
        migrations.AlterModelOptions(
            name='dagskassa',
            options={'ordering': ('date',), 'verbose_name': 'dagskassa', 'verbose_name_plural': 'dagskassor'},
        ),
        migrations.AlterField(
            model_name='dagskassa',
            name='comment',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dagskassa',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
