# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Economy', '0003_auto_20161121_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
