# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Economy', '0006_auto_20161124_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Economy.Employee', verbose_name='anställd'),
        ),
    ]
