# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Economy', '0008_auto_20161204_2031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dagskassa',
            unique_together=set([('date', 'cash', 'card', 'signature')]),
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together=set([('employee', 'date', 'added')]),
        ),
    ]
