# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleantask',
            name='CleanDay',
        ),
        migrations.DeleteModel(
            name='CleanType',
        ),
        migrations.DeleteModel(
            name='CleaningDays',
        ),
        migrations.DeleteModel(
            name='CleanTask',
        ),
    ]
