# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bikeKeyNo', models.IntegerField()),
                ('rentOutCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BikesBooking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Bikes')),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=7)),
                ('card', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cafeSales', models.DecimalField(decimal_places=2, max_digits=7)),
                ('iceCreamSales', models.DecimalField(decimal_places=2, max_digits=7)),
                ('foodShopSales', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bikeSales', models.DecimalField(decimal_places=2, max_digits=7)),
                ('booksSales', models.DecimalField(decimal_places=2, max_digits=7)),
                ('other12Sales', models.DecimalField(decimal_places=2, max_digits=7)),
                ('other25Sales', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='CleanDay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperatureMeasured', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CleanPoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pointType', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('cleanTask', models.CharField(max_length=200)),
                ('maxTemp', models.IntegerField()),
                ('minTemp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Damages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damageType', models.CharField(max_length=200)),
                ('repaired', models.BooleanField(default=False)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Bikes')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=50)),
                ('personNo', models.IntegerField()),
                ('wage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('phoneNumber', models.IntegerField()),
                ('eMailAdress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='damages',
            name='repairedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Employee'),
        ),
        migrations.AddField(
            model_name='cleanday',
            name='Employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.Employee'),
        ),
        migrations.AddField(
            model_name='cleanday',
            name='cleanDate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Date'),
        ),
        migrations.AddField(
            model_name='cleanday',
            name='cleanPoint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.CleanPoint'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='countingDay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Date'),
        ),
        migrations.AddField(
            model_name='bikesbooking',
            name='bookingDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Date'),
        ),
        migrations.AddField(
            model_name='bikesbooking',
            name='bookingGuest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Guest'),
        ),
    ]
