# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikesbooking',
            name='bikes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Bikes'),
        ),
        migrations.AlterField(
            model_name='bikesbooking',
            name='bookingDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Date'),
        ),
        migrations.AlterField(
            model_name='bikesbooking',
            name='bookingGuest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Guest'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='countingDay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Date'),
        ),
        migrations.AlterField(
            model_name='cleanday',
            name='Employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Employee'),
        ),
        migrations.AlterField(
            model_name='cleanday',
            name='cleanDate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Date'),
        ),
        migrations.AlterField(
            model_name='cleanday',
            name='cleanPoint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.CleanPoint'),
        ),
        migrations.AlterField(
            model_name='damages',
            name='bike_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Bikes'),
        ),
        migrations.AlterField(
            model_name='damages',
            name='repairedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Employee'),
        ),
    ]
