# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20161016_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bikeKeyNo', models.IntegerField()),
                ('rentOutCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cashier',
            name='countingDay',
        ),
        migrations.RemoveField(
            model_name='cleanday',
            name='cleanDate_id',
        ),
        migrations.AlterField(
            model_name='bikesbooking',
            name='bikes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Bike'),
        ),
        migrations.AlterField(
            model_name='cleanday',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='damages',
            name='bike_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Bike'),
        ),
        migrations.DeleteModel(
            name='Bikes',
        ),
    ]
