# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20161227_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikesBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_bike', to='database.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='LunchBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_lunches', to='database.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoomsBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfGuests', models.PositiveIntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_rooms', to='database.Booking')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemsbooking',
            name='booking',
        ),
        migrations.AddField(
            model_name='utilities',
            name='number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bikeavailable',
            name='bookings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availableBike', to='database.BikesBooking'),
        ),
        migrations.AlterField(
            model_name='bikeextra',
            name='attached_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bikeextra', to='database.Bike', verbose_name='knuten till cykel'),
        ),
        migrations.AlterField(
            model_name='damages',
            name='discoveredBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discovered_by', to='Economy.Employee', verbose_name='upptäckt av'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='bookings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='database.LunchBooking'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='bookings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='database.LunchBooking'),
        ),
        migrations.DeleteModel(
            name='ItemsBooking',
        ),
        migrations.AddField(
            model_name='rooms',
            name='bookings',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='booked_room', to='database.RoomsBooking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomsavailable',
            name='bookings',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='available_rooms', to='database.RoomsBooking'),
            preserve_default=False,
        ),
    ]
