# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20161017_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikesbooking',
            name='numberOfGuests',
            field=models.IntegerField(default=0),
        ),
    ]
