# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20161229_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_room', to='database.RoomsBooking'),
        ),
    ]
