# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-01 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20170101_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeextra',
            name='attached_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bikeextra', to='database.Bike', verbose_name='knuten till cykel'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='bookings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='database.LunchBooking'),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='bookings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='database.LunchBooking'),
        ),
    ]
