# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_bike_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='BikesBooking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.BikesBooking'),
        ),
    ]
