# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20170101_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchbooking',
            name='type',
            field=models.CharField(choices=[('vegetarian', 'vegetarisk'), ('meat', 'kallskuret'), ('fish', 'Vätternröding')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
