# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_date_bikesbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='BikesBooking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='database.BikesBooking'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
