# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20170101_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchbooking',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
