# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20161019_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikesbooking',
            name='bikes',
        ),
        migrations.RemoveField(
            model_name='bikesbooking',
            name='bookingGuest',
        ),
        migrations.RemoveField(
            model_name='bikesbooking',
            name='numberOfGuests',
        ),
        migrations.RemoveField(
            model_name='date',
            name='BikesBooking',
        ),
        migrations.AlterField(
            model_name='bike',
            name='booking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.BikesBooking'),
        ),
    ]
