# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_lunchbooking_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikesbooking',
            options={'verbose_name': 'cykelbokning', 'verbose_name_plural': 'cykelbokningar'},
        ),
        migrations.AlterModelOptions(
            name='lunchbooking',
            options={'verbose_name': 'lunchbokning', 'verbose_name_plural': 'lunchbokningar'},
        ),
        migrations.AlterModelOptions(
            name='roomsbooking',
            options={'verbose_name': 'rumsbokning', 'verbose_name_plural': 'rumsbokningar'},
        ),
        migrations.AddField(
            model_name='bikesbooking',
            name='from_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikesbooking',
            name='full_days',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bikesbooking',
            name='to_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bikeavailable',
            name='bike',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.PROTECT, to='database.Bike'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bikeavailable',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availableBike', to='database.BikesBooking'),
        ),
        migrations.AlterField(
            model_name='roomsbooking',
            name='numberOfGuests',
            field=models.PositiveIntegerField(verbose_name='antal gäster'),
        ),
        migrations.AlterUniqueTogether(
            name='bikeavailable',
            unique_together=set([('bike', 'available_date')]),
        ),
    ]
