# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20161112_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField(verbose_name='Booking_Date')),
                ('numberOfGuests', models.IntegerField(default=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='bikesbooking',
            name='bikes',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='damages',
            name='repairedBy',
        ),
        migrations.AlterField(
            model_name='guest',
            name='eMailAdress',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='firstName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='lastName',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='BikesBooking',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='booking',
            name='bikes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Bike'),
        ),
    ]
