# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bikeavailable',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='bikeavailable',
            index_together=set([('bike', 'available_date')]),
        ),
    ]
