# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20170113_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikeavailable',
            options={'ordering': ['available_date', 'bike', 'available'], 'verbose_name': 'tillgänglighet cykel', 'verbose_name_plural': 'tillgänglighet cyklar'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Händelse', 'verbose_name_plural': 'Händelser'},
        ),
        migrations.AddField(
            model_name='bikesbooking',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bike', to='database.Bike'),
        ),
    ]
