# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0011_auto_20161112_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personNo', models.IntegerField()),
                ('wage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='damages',
            name='bike_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Bike'),
        ),
        migrations.AddField(
            model_name='damages',
            name='repairedBy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.Employee'),
        ),
    ]
