# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20170115_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
    ]
