# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_guest_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeExtraBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DurationField()),
                ('full_day', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Booking', to='database.Booking')),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bike_extra', to='database.BikeExtra')),
            ],
        ),
    ]
