# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_bikeextrabooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest',
            new_name='guest_for_booking',
        ),
        migrations.AddField(
            model_name='guest',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Booking'),
        ),
        migrations.AlterField(
            model_name='bikeextrabooking',
            name='to_date',
            field=models.DurationField(choices=[(datetime.timedelta(1), '1 Dag'), (datetime.timedelta(2), '2 Dagar'), (datetime.timedelta(3), '3 Dagar'), (datetime.timedelta(4), '4 Dagar'), (datetime.timedelta(5), '5 Dagar'), (datetime.timedelta(6), '6 Dagar'), (datetime.timedelta(7), '7 Dagar')]),
        ),
    ]
