# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20161207_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('bike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Bike')),
            ],
        ),
        migrations.AddField(
            model_name='accomodation',
            name='slug',
            field=models.SlugField(default='/'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='slug',
            field=models.SlugField(default='/'),
        ),
    ]
