# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_guestuser_staff'),
        ('database', '0019_auto_20161211_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='incheckad (J/N)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_out',
            field=models.BooleanField(default=False, verbose_name='utcheckad(J/N)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.GuestUser', verbose_name='gäst'),
        ),
    ]
