# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 17:15
from __future__ import unicode_literals

import database.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_guestuser_staff'),
        ('database', '0021_auto_20161211_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('newsletter', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('auth.guestuser', models.Model),
        ),
        migrations.DeleteModel(
            name='GuestExtra',
        ),
        migrations.CreateModel(
            name='BikeBooking',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'cykelbokningar',
                'verbose_name': 'cykelbokning',
            },
            bases=('database.booking',),
            managers=[
                ('ojects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Bokning', 'verbose_name_plural': 'bokningar'},
        ),
        migrations.AddField(
            model_name='booking',
            name='booking',
            field=models.PositiveIntegerField(default=database.models.calc_booking_no, unique=True, primary_key=True, serialize=False, verbose_name='boknings id'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='accomodation',
            field=models.ManyToManyField(blank=True, related_name='accomodation', to='database.Accomodation', verbose_name='boende'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bikes',
            field=models.ManyToManyField(blank=True, related_name='bikes', to='database.Bike', verbose_name='cyklar'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True, verbose_name='bokningsdatum'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='endDate',
            field=models.DateField(null=True, verbose_name='datum för hemresa'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDate',
            field=models.DateField(null=True, verbose_name='datum för avresa'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('B', 'Cykel'), ('A', 'Boende'), ('L', 'Lunch'), ('P', 'Paket'), ('E', 'Event')], default='B', max_length=25, verbose_name='bokningstyp'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='utilities',
            field=models.ManyToManyField(blank=True, related_name='utilities', to='database.Utilities', verbose_name='tillbehör'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='database.Accomodation', verbose_name='anläggning'),
        ),
    ]
