# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 22:47
from __future__ import unicode_literals

import database.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20161215_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bokning', 'verbose_name_plural': 'bokningar'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking',
            field=models.PositiveIntegerField(default=database.models.calc_booking_no, primary_key=True, serialize=False, verbose_name='boknings id'),
        ),
    ]
